name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity. it will be closed in 7 days...'
        stale-pr-message: 'This Pull-request is stale because it has been open for 30 days with no activity. it will be closed in 7 days...'
        stale-issue-label: 'inactive-issue,stale'
        exempt-issue-labels: 'awaiting-approval,work-in-progress'
        stale-pr-label: 'inactive-pr,stale'
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
        exempt-all-issue-assignees: true
        days-before-stale: 30
        days-before-close: 650
        remove-issue-stale-when-updated: true
        remove-pr-stale-when-updated: true
        close-pr-message: 'Existing merge conflicts have not been addressed. This PR is considered abandoned.'
